### ISSUE TITLE
-l flag shows same monitor twice

### ISSUE THREAD

**Issue by shadoWalker89** [Crozzers/screen_brightness_control#7]
I have a laptop and an external monitor

When i run `python -m screen_brightness_control -l`

If both screens (integrated) and external are on and i'm showing the same content on both screens `Duplicate` or `Second screen only` options from `windows + p` shortcut i get this output which is correct
```
Display 0: Asus AUO63ED
Display 1: Samsung 0D2C
```

If i use `Extend` option i get the integrated monitor twice and after that the external monitor

```
Display 0: Asus AUO63ED
Display 1: Asus 63ED
Display 2: Samsung 0D2C
```

If i use `PC screen only` or disconnect the external monitor i get the integrated laptop twice

```
Display 0: Asus AUO63ED
Display 1: Asus 63ED
```

Also if i try to set the brightness using the `-d` flag it only works when i use the index 0 if i use the index 1 i get this error
This traceback is using the --verbose flag
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 537, in set_brightness
    return method(value, **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 672, in set_brightness
    return __set_and_get_brightness(value, display=display, method=method, meta_method='set', **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 631, in __set_and_get_brightness
    raise Exception(msg)
Exception:
        no valid output was received from brightness methods

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__main__.py", line 45, in <module>
    SBC.set_brightness(args.set, display = args.display, method = args.method, verbose_error = args.verbose)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 540, in set_brightness
    raise ScreenBrightnessError from e
screen_brightness_control.ScreenBrightnessError: Cannot set/retrieve brightness level
```

This behavior is the same on the 0.6.2 and the dev branch

**Comment by Crozzers** [comment]
That's probably because duplicates are normally filtered out by their EDID strings. If a monitor doesn't play nicely with WMI then it will have no EDID string and the "serial" number will be something different as well.
I'll work on this.

As for the `-d` flag not working I hope that it's something to do with the duplicate monitors

**Comment by shadoWalker89** [comment]
The -d flag does not work only with the duplicate entry

If we take this example
```
Display 0: Asus AUO63ED
Display 1: Asus 63ED
Display 2: Samsung 0D2C
```

-d 0 works
-d 1 does not work
-d 2 works

The -d has only an issue with the duplicate wrong entry which is understandable since it's not a real one

**Comment by Crozzers** [comment]
Tweaked `sbc.windows.VCP.get_display_info` so that it merges information from `WmiMonitorID` with `win32api`, meaning that most of the time it should take info from `WmiMonitorID` but if that fails it takes from `win32api`.
This should mean that if we can at least get the serial number from the monitor reliably then there shouldn't be any more duplicates.

If you could test this that would be awesome

**Comment by shadoWalker89** [comment]
The integrated monitor still show up twice

**Comment by Crozzers** [comment]
My bad. I added a check to see if it's a laptop screen in the `VCP` method. Should work now

**Comment by shadoWalker89** [comment]
So there is good news and bad news
The good news is that the duplicate entry is not longer there

![image](https://user-images.githubusercontent.com/1449151/105977207-6242c700-6091-11eb-9cc3-7768a5787daa.png)

The bad news is now when i try to set the brightness with or without the -d flag it works only on the integrated monitor.

When i do it without the -d flag i get no errors but only works for the integrated monitor

`python -m screen_brightness_control -s 20`

When i use the -d flag i get an error

`python -m screen_brightness_control -s 20 -d 1`

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 537, in set_brightness
    return method(value, **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 673, in set_brightness
    return __set_and_get_brightness(value, display=display, method=method, meta_method='set', **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 632, in __set_and_get_brightness
    raise Exception(msg)
Exception:
        no valid output was received from brightness methods

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__main__.py", line 45, in <module>
    SBC.set_brightness(args.set, display = args.display, method = args.method, verbose_error = args.verbose)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 540, in set_brightness
    raise ScreenBrightnessError from e
screen_brightness_control.ScreenBrightnessError: Cannot set/retrieve brightness level
```

**Comment by Crozzers** [comment]
I have been unable to reproduce the error. Could you send the output of
```python
import screen_brightness_control as s
print(s.list_monitors_info())
```
and
```python
import screen_brightness_control as s
print(s.windows.WMI.set_brightness(100, display=0))
```
and
```python
import screen_brightness_control as s
print(s.windows.VCP.set_brightness(100, display=0))
```

And I assume that the external monitor is turned on and the input source is set to the laptop because it won't work otherwise

**Comment by shadoWalker89** [comment]
I performed all the tests below with both screens on and i'm using the `Extend` option from `Windows + P`

Screen 0 is the Asus AUO63ED (integrated)
Screen 1 is the Samsung 0D2C (external)

```python
import screen_brightness_control as s
print(s.list_monitors_info())
```

`[{'name': 'Asus AUO63ED', 'model': 'AUO63ED', 'model_name': None, 'serial': '4&3b2d1c8b&0&UID265988_0', 'manufacturer': 'Asus', 'manufacturer_id': 'AUO', 'index': 0, 'method': <class 'screen_brightness_control.windows.WMI'>, 'edid': 'XXX'}, {'name': 'Samsung 0D2C', 'model': '0D2C', 'model_name': None, 'serial': 'HTQK300272', 'manufacturer': 'Samsung', 'manufacturer_id': 'SAM', 'index': 0, 'method': <class 'screen_brightness_control.windows.VCP'>, 'edid': 'XXX'}]`


```python
import screen_brightness_control as s
print(s.windows.WMI.set_brightness(100, display=0))
```
It actually changes the brightness and returns prints `100`

```python
import screen_brightness_control as s
print(s.windows.VCP.set_brightness(100, display=0))
```
It does not change the brightness and print `None`

Just to be sure that we are on the same page, when i used the package it works with the integrated monitor, but the external monitor is the one that is not changing it's brightness.

So i went ahead and also run these

```python
import screen_brightness_control as s
print(s.windows.WMI.set_brightness(100, display=1))
```

It does not work and it throws this error
```Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print(s.windows.WMI.set_brightness(100, display=1))
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 131, in set_brightness
    indexes = [i['index'] for i in filter_monitors(display=display, method='wmi')]
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 434, in filter_monitors
    raise LookupError(msg)
LookupError: no monitors found with name/serial/model/edid/index of "1" with method of "wmi"
```

```python
import screen_brightness_control as s
print(s.windows.VCP.set_brightness(100, display=1))
```

It does not work and it throws this error
```Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print(s.windows.VCP.set_brightness(100, display=1))
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 518, in set_brightness
    indexes = [i['index'] for i in filter_monitors(display = display, haystack = VCP.get_display_info())]
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 434, in filter_monitors
    raise LookupError(msg)
LookupError: no monitors found with name/serial/model/edid/index of "1"
```

And after that i also tried changing the brightness with the two methods without display parameter

```python
import screen_brightness_control as s
print(s.windows.WMI.set_brightness(100))
```
Changes the brightness only for the integrated monitor which is `Asus AUO63ED`

```python
import screen_brightness_control as s
print(s.windows.VCP.set_brightness(100))
```
Changes the brightness only for the external monitor which is `Samsung 0D2C`

**Comment by Crozzers** [comment]
Perhaps this is a problem with the laptop filtering. Perhaps the number of physical monitor handles returned by `sbc.windows.VCP.iter_physical_monitors` doesn't match the number of displays returned by `sbc.windows.VCP.get_display_info`
Could you try
```python
import screen_brightness_control as s
for m in s.windows.VCP.iter_physical_monitors():
    print(m)
```
It will probably print `None` or `1` or something. The contents of the message isn't important but the number of times something gets printed

**Comment by shadoWalker89** [comment]
```
None
None
```

**Comment by shadoWalker89** [comment]
Just to put things into perspective

in version 0.6.2

doing 

`python -m screen_brightness_control -l`

```
Display 0: Asus AUO63ED
Display 1: Asus AUO63ED
Display 2: Samsung SAM0D2C
```

Doing `python -m screen_brightness_control -s 10 -d 2` will change the brightness but prints this error

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 220, in set_brightness
    return method(value, **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 819, in set_brightness
    return __set_and_get_brightness(value, display=display, method=method, meta_method='set', **kwargs)
  File "C:\Python38\lib\site-packages\screen_brightness_control\windows.py", line 778, in __set_and_get_brightness
    raise Exception(msg)
Exception:
        Samsung SAM0D2C (5&4cb9233&0&UID4352) -> IndexError: list index out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__main__.py", line 49, in <module>
    SBC.set_brightness(args.set, **kw)
  File "C:\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 223, in set_brightness
    raise ScreenBrightnessError from e
screen_brightness_control.ScreenBrightnessError: Cannot set/retrieve brightness level
```

**Comment by shadoWalker89** [comment]
I tried the same stuff on another laptop and i can confirm that the issue is the same

**Comment by Crozzers** [comment]
Ok, changed when the monitor's `'index'` is incremented. This shouldn't change anything on the top level but lower down it may cause issues. So
```python
import screen_brightness_control as s
s.windows.VCP.set_brightness(50, display=0)
```
might become
```python
import screen_brightness_control as s
s.windows.VCP.set_brightness(50, display=1)
```
with no valid displays in the 0th index. However, if you use the higher level functions this shouldn't affect you

**Comment by shadoWalker89** [comment]
As we established in https://github.com/Crozzers/screen_brightness_control/issues/7#issuecomment-768437605
Changing the brightness with `VCP` only works with the external monitor
So the following results are for the external one Samsung


![image](https://user-images.githubusercontent.com/1449151/105977207-6242c700-6091-11eb-9cc3-7768a5787daa.png)

Only this works and that is when the integrated monitor is turned off, or i'm using the `Duplicate` option
```python
import screen_brightness_control as s
s.windows.VCP.set_brightness(50, display=0)
```
If i switch to the `Extend` option it does not work and does not print any errors

As i mentioned in this https://github.com/Crozzers/screen_brightness_control/issues/7#issuecomment-767868109
It worked with -d 2 when we had the duplicate entry, maybe the problem is when merging from the two sources you are forgetting something ?

**Comment by Crozzers** [comment]
The `VCP` class is designed to only work with external monitors and the `WMI` class is designed to only work with internal monitors. 
So setting the brightness for "display 0" on `WMI` is not the same as setting the brightness for "display 0" in `VCP`.
The results from both methods gets combined when the top-level brightness functions are called. I don't think this is the issue, however.
So does `python -m screen_brightness_control -s 100 -d 1` still not work on the dev branch?

And if you try running
```python
import screen_brightness_control as s
s.__cache__.enabled = False
print(s.set_brightness(100, display=0))
print(s.set_brightness(100, display=1))
```
does that make a difference?

**Comment by shadoWalker89** [comment]
`python -m screen_brightness_control -s 100 -d 1` works on the dev branch

Running the code will output
```
100
100
```

**Comment by Crozzers** [comment]
So can the issue be considered fixed?
The issue with duplicates was resolved and the dev branch works so I think it's fixed.

**Comment by shadoWalker89** [comment]
No it's not fixed and this is why

When i opened this issue doing this `python -m screen_brightness_control -s 0` will work on both screens on every situation even using `Extended` mode but now in the current situation of the dev branch it does not
I feel like this got out of hand, maybe it's better to leave it with duplicate entries than this.

Maybe you should reset the dev branch to the way it was just after we closed the previous issue and leave like that or start over again from that state.

**Comment by Crozzers** [comment]
I'll reset the dev branch and re-open the issue in a hope of starting with clearer goals and thoughts.
I agree that this issue got a bit out of hand due to there being numerous problems so it felt a bit like playing whack-a-mole.
The fact that I am unable to test the issues myself is also a major hurdle but one that doesn't have a reasonable solution.

If you could submit a bulletpoint summary of the problems that would be a great help in focusing the 'mole whacking' efforts

**Comment by Crozzers** [comment]
I have created a new branch called 'fix/issue7' as an experimental branch where messy changes and commits can be made without mucking up dev or master. Once we get it working I can then port the code over without too much hassle
